export const elements = {
    form: document.getElementById("translate-form"),
    sourceText: document.getElementById("source-text"),
    sourceLanguage: document.getElementById("source-language"),
    targetLanguage: document.getElementById("target-language"),
    sourceSelectRoot: document.getElementById("source-select"),
    targetSelectRoot: document.getElementById("target-select"),
    sourceLanguageButton: document.getElementById("source-language-button"),
    targetLanguageButton: document.getElementById("target-language-button"),
    sourceLanguageLabel: document.getElementById("source-language-label"),
    targetLanguageLabel: document.getElementById("target-language-label"),
    sourceLanguageFlag: document.getElementById("source-language-flag"),
    targetLanguageFlag: document.getElementById("target-language-flag"),
    sourceLanguageOptions: document.getElementById("source-language-options"),
    targetLanguageOptions: document.getElementById("target-language-options"),
    translatedText: document.getElementById("translated-text"),
    translateButton: document.getElementById("translate-button"),
    translateButtonSpinner: document.getElementById("translate-button-spinner"),
    translateButtonLabel: document.getElementById("translate-button-label"),
    swapButton: document.getElementById("swap-button"),
    copyButton: document.getElementById("copy-button"),
    copyIconDefault: document.getElementById("copy-icon-default"),
    copyIconSuccess: document.getElementById("copy-icon-success"),
    statusMessage: document.getElementById("status-message"),
    errorMessage: document.getElementById("error-message"),
    charCounter: document.getElementById("char-counter"),
    lengthWarning: document.getElementById("length-warning"),
}

export const select_configs = {
    source: {
        root: elements.sourceSelectRoot,
        select: elements.sourceLanguage,
        trigger: elements.sourceLanguageButton,
        label: elements.sourceLanguageLabel,
        flag: elements.sourceLanguageFlag,
        options: elements.sourceLanguageOptions,
    },
    target: {
        root: elements.targetSelectRoot,
        select: elements.targetLanguage,
        trigger: elements.targetLanguageButton,
        label: elements.targetLanguageLabel,
        flag: elements.targetLanguageFlag,
        options: elements.targetLanguageOptions,
    },
}
